mytest.py: Check if self.summary has value
After commit ae7f6ae it is possible to get the following error when osd3dsetup is not installed.

File "/usr/lib/enigma2/python/mytest.py", line 315, in pushSummary
    self.summary.hide()
AttributeError: 'list' object has no attribute 'hide'

Checking if self.summary has value fixes the issue.